import { Principal } from "@dfinity/principal";
import * as estateDaoNft from "../../dfx_generated/estate_dao_nft/estate_dao_nft.did.js";
import * as provision from "../../dfx_generated/provision/provision.did.js";

export const SamplePropertyInit = {
  year_built: 0,
  monthly_utilities: 0,
  total_monthly_cost: 0,
  average_5_year_roi: 0,
  documents: [],
  yields: 0,
  llc_monthly_franchise_tax: 0,
  country: "",
  occupied: false,
  monthly_cash_flow: 0,
  crime_score: 0,
  monthly_rent: 0,
  beds: 0,
  city: "",
  total_5_year_irr: 0,
  logo: "",
  property_insurance: 0,
  name: "",
  affordability: 0,
  expense_to_income_ratio: 0,
  square_footage: 0,
  description: "",
  flood_zone: false,
  initial_maintenance_reserve: 0,
  vacancy_rate: 0,
  projected_appreciation: 0,
  underlying_asset_price: 0,
  asset_canister: Principal.anonymous(),
  state: "",
  property_taxes: 0,
  price_per_sq_foot: 0,
  property_managment_fee: 0,
  market_description: "",
  cap_rate: 0,
  baths: 0,
  platform_closing_fee: 0,
  property_owner: Principal.anonymous(),
  school_score: 0,
  last_renovated: 0,
  projected_rent: 0,
  average_rent: 0,
  min_investment: 0,
  median_home_sale_price: 0,
  symbol: "",
  coordinates: "",
  annual_popullation_growth: 0,
};

export const SamplePropertyUpdate = {
  year_built: [] as [],
  monthly_utilities: [] as [],
  total_monthly_cost: [] as [],
  average_5_year_roi: [] as [],
  documents: [] as [],
  yields: [] as [],
  llc_monthly_franchise_tax: [] as [],
  country: [] as [],
  occupied: [] as [],
  monthly_cash_flow: [] as [],
  crime_score: [] as [],
  monthly_rent: [] as [],
  beds: [] as [],
  city: [] as [],
  total_5_year_irr: [] as [],
  logo: [] as [],
  property_insurance: [] as [],
  name: [] as [],
  affordability: [] as [],
  expense_to_income_ratio: [] as [],
  square_footage: [] as [],
  description: [] as [],
  flood_zone: [] as [],
  initial_maintenance_reserve: [] as [],
  vacancy_rate: [] as [],
  projected_appreciation: [] as [],
  underlying_asset_price: [] as [],
  asset_canister: [] as [],
  state: [] as [],
  property_taxes: [] as [],
  price_per_sq_foot: [] as [],
  property_managment_fee: [] as [],
  market_description: [] as [],
  cap_rate: [] as [],
  baths: [] as [],
  platform_closing_fee: [] as [],
  school_score: [] as [],
  last_renovated: [] as [],
  projected_rent: [] as [],
  average_rent: [] as [],
  min_investment: [] as [],
  median_home_sale_price: [] as [],
  symbol: [] as [],
  coordinates: [] as [],
  annual_popullation_growth: [] as [],
} as Parameters<estateDaoNft._SERVICE["update_metadata"]>[0];

export const SamplePropertyRequest = {
  year_built: 0,
  monthly_utilities: 0,
  total_monthly_cost: 0,
  average_5_year_roi: 0,
  documents: [],
  yields: 0,
  llc_monthly_franchise_tax: 0,
  country: "",
  occupied: false,
  monthly_cash_flow: 0,
  crime_score: 0,
  monthly_rent: 0,
  beds: 0,
  city: "",
  total_5_year_irr: 0,
  logo: "",
  property_insurance: 0,
  name: "",
  affordability: 0,
  expense_to_income_ratio: 0,
  square_footage: 0,
  description: "",
  flood_zone: false,
  initial_maintenance_reserve: 0,
  vacancy_rate: 0,
  projected_appreciation: 0,
  underlying_asset_price: 0,
  state: "",
  property_taxes: 0,
  price_per_sq_foot: 0,
  property_managment_fee: 0,
  market_description: "",
  cap_rate: 0,
  baths: 0,
  platform_closing_fee: 0,
  school_score: 0,
  last_renovated: 0,
  projected_rent: 0,
  average_rent: 0,
  min_investment: 0n,
  median_home_sale_price: 0,
  symbol: "",
  coordinates: "",
  annual_popullation_growth: 0,
} as Parameters<provision._SERVICE["add_property_request"]>[0];
