name: Test Canisters
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version
      
      - name: Install npm packages
        run: yarn install

      - name: Start DFX Server
        run: dfx start --background
      
      - name: Create canisters
        run: dfx canister create --all

      - name: Build canister
        run: yarn build

      - name: Run test
        run: yarn test